#!/bin/bash
#Copyright 2008-2009 Christopher Smart, under GPLv3 (a copy included in COPYING)

#Hi there. This script mounts an external device and rsyncs the ubuntu repository and clamav virus definitions.

# Some bash things:
# exists: -e
# is a file: -f
# is a directory: -d
# returned value is not null: -n
# is zero: -z
# something is equal to something else: =
# something is NOT equal to something else: != 
# or -o
# and -a

if [ -z "`ps ax |grep [u]pdate-system`" ]
then
	echo "Do not run this script directly, it is called by 'update-system'"
	echo "Exiting"
	exit 1
fi

#Variables should exist in the shell as they were exported by the 'update-system' script

#Check if this is a new install
if [ "$STATUS" = "new" ]
then
	echo "Looks like you want to set up a new server, let's do it.."
	sleep 2
	#Install apache
	if [ -z "`dpkg -l |grep apache2`" ]
		then apt-get -qq install apache2
	fi
	#Set up deb archive links for clients
	mkdir -p /var/www 2>/dev/null
	cd /var/www/
	for x in `ls $MOUNTPOINT/data/debs`
	do
		ln -sf /data/debs/$x
	done
	#Add update drive to fstab
	if [ -z "`grep $DEVICE /etc/fstab`" ]
	then
		echo "$DEVICE $MOUNTPOINT auto noauto,noatime 0 0" >> /etc/fstab
	fi
	#set up sources.lst
	if [ -z "`grep "/data/debs/" /etc/apt/sources.list`" ]
	then
		echo "deb file:///data/debs/ubuntu $DISTRO main restricted universe multiverse" > /etc/apt/sources.list
		echo "deb file:///data/debs/ubuntu $DISTRO-updates main restricted universe multiverse" >> /etc/apt/sources.list
		echo "deb file:///data/debs/ubuntu $DISTRO-security main restricted universe multiverse" >> /etc/apt/sources.list
	fi
	apt-get -qq install bind9 vim postfix htop logwatch dovecot-imap dovecot-common postgresql-8.3 nfs-kernel-server

	#set syntax and jump in vimrc (use sed?)
	#set bash colours
	#set up ssh keys
	#create dpuser and add groups
	#configure nfs
	#set up /etc/hosts localhost to point to fqdn 
	#configure dns


	echo "Setting up first time server - SUCCESS" >> $COMPLETEFILE
fi

clear
echo "-----------------------"
echo "Synchronising updates.."
rsync -a $MOUNTPOINT/data /

echo "Synchronisation - SUCCESS" >> $COMPLETEFILE

if [ -n "`dpkg -l |grep apache2`" -a -d "/var/www" ]
	then
		echo "------------------------------------"
		echo "Updating online virus definitions.."
		rsync -a /data/clamav/db/*cvd /var/www/
		echo "Copy ClamAV definitions to Apache - SUCCESS" >> $COMPLETEFILE
	else
		echo "------------------------------------"
		echo "Skipping antivirus update."
		echo "Copy ClamAV definitions to Apache - SKIPPED" >> $COMPLETEFILE
fi

#Quietly update apt database
echo "-----------------------------------------"
echo "Updating package local package database.."
apt-get -qq update
echo "Update apt database - SUCCESS" >> $COMPLETEFILE

#Print datestamp of virus defs
echo "-----------------------------------------"
echo "Checking ClamAV definitions.."

if [ "`date +%Y-%m-%d`" != "`ls -l /data/clamav/db/ |grep daily.cvd |awk {'print $6'}`" ]
	then
		echo "Today is `date +%Y-%m-%d`."
		echo "Latest daily.cvd is dated `ls -l /data/clamav/db/ |grep daily.cvd |awk {'print $6'}`."
		echo "Latest main.cvd is dated `ls -l /data/clamav/db/ |grep main.cvd |awk {'print $6'}`."
		echo "Please compare the dates."
		echo ""
		echo "** HIT ENTER TO CONTINUE **"
		read
		echo "ClamAV definitions update - CHECK DATES" >> $COMPLETEFILE
	else
		echo "ClamAV definitions update - SUCCESS" >> $COMPLETEFILE
fi

#If this is marlin, backup the Amanda config files
if [ `hostname` = "marlin.dr.lan" ]
	then
		echo "--------------------------------"
		echo "Backing up Amanda config files.."
		mkdir -p $MOUNTPOINT/backup/marlin/etc/ 2>/dev/null
		rsync -a /etc/amanda* $MOUNTPOINT/backup/marlin/etc/
		rsync -a /usr/local/bin $MOUNTPOINT/backup/marlin/usr/local/
		echo "--------------------------------"
		echo "Amanda config backup - SUCCESS" >> $COMPLETEFILE
	else
		echo "-----------------------------"
fi

#Clean up error file
rm $ERRORFILE 2>/dev/null

#Summary of update
echo ""
echo "SUMMARY"
echo "-------"
echo "`cat $COMPLETEFILE`"
echo ""

#Clean up
rm $COMPLETEFILE
