#! /bin/bash
#
# Script to be run via cron to perform a nightly backup of the Xena repository.
# Uses rsync for the backup and sends email to the admin on completion.
#
MAIL_TO="michael.carden@naa.gov.au matthew.oliver@naa.gov.au christopher.smart@naa.gov.au alan.langley@naa.gov.au"
RETRY_ATTEMPTS=5
tmp="/tmp/xenabackupresults"
echo "This message is generated by the Xena source repository backup script." > $tmp
echo "**********************************************************************" >> $tmp
echo "" >> $tmp
cd /backups/xena

i=0
finish=0
while [ $finish -eq 0 ]
do
	rsync -av rsync://xena.git.sourceforge.net/gitroot/xena/xena/ . >> $tmp
	if [ $? -ne 0 ]
	then
		#FAILED
		let "i+=1"
		if [ $i -gt $RETRY_ATTEMPTS ]
		then
			finish=1
		fi
	else
		finish=1
	fi
done

if [ $i -gt $RETRY_ATTEMPTS ]
then
	echo "Failed to rsync all $RETRY_ATTEMPTS attempts failed!" > $tmp
fi

mailx -s "Xena source backup results $(date)" $MAIL_TO < $tmp

rm $tmp

