#!/bin/bash

#This script rsyncs a local Fedora mirror

#Variables
DATE=`date +%Y%d%m%H%m`
LOG=/var/log/update-fedora-mirror-$DATE.log
CURRENT_DIR=`pwd`

#Variables - mirror
LOCAL_MIRROR=/data
#Be careful of trailing fedora-enchilada directory if using another mirror instead of aarnet
#FEDORA_MIRROR=mirror.aarnet.edu.au
FEDORA_MIRROR=mirror.internode.on.net/fedora-enchilada
RPMFUSION_MIRROR=download1.rpmfusion.org

#Mirrors:
#rsync://mirror.internode.on.net/fedora-enchilada
#rsync://mirror.aarnet.edu.au/fedora/linux
#rsync://download.fedora.redhat.com/fedora-enchilada
#http://mirrors.fedoraproject.org/publiclist/Fedora/12/
#http://rpmfusion.org/Mirrors

if [ $# -lt 1 ]
then
	echo "no variable passed"
	exit 1
fi

#Variables - release
RELEASE_VERSION=$1
BASE_ARCH=x86_64

#Variables - directory structures
FEDORA_IMAGES=fedora/linux/releases/$RELEASE_VERSION/Fedora/$BASE_ARCH/os
FEDORA_MAIN=fedora/linux/releases/$RELEASE_VERSION/Everything/$BASE_ARCH/os
FEDORA_UPDATES=fedora/linux/updates/$RELEASE_VERSION/$BASE_ARCH
RPMFUSION_FREE=rpmfusion/free/fedora/releases/$RELEASE_VERSION/Everything/$BASE_ARCH/os
RPMFUSION_FREE_UPDATES=rpmfusion/free/fedora/updates/$RELEASE_VERSION/$BASE_ARCH
RPMFUSION_NONFREE=rpmfusion/nonfree/fedora/releases/$RELEASE_VERSION/Everything/$BASE_ARCH/os
RPMFUSION_NONFREE_UPDATES=rpmfusion/nonfree/fedora/updates/$RELEASE_VERSION/$BASE_ARCH

#Variables - excludes
EXCLUDES="i386\nppc\nppc64\nsource\nSRPMS\ncore\ndebug"
EXCLUDES_FILE=/tmp/rsync-excludes-$DATE

#Set Proxy
export http_proxy="http://localhost:5865"

#Create excludes file
echo -e $EXCLUDES > $EXCLUDES_FILE

#Create directory structures, in case they don't exist already
for x in $LOCAL_MIRROR/$FEDORA_IMAGES $LOCAL_MIRROR/$FEDORA_MAIN $LOCAL_MIRROR/$FEDORA_UPDATES $LOCAL_MIRROR/$RPMFUSION_FREE $LOCAL_MIRROR/$RPMFUSION_FREE_UPDATES $LOCAL_MIRROR/$RPMFUSION_NONFREE $LOCAL_MIRROR/$RPMFUSION_NONFREE_UPDATES $LOCAL_MIRROR/raw
do
	mkdir -p $x &>/dev/null
done

#Fedora images repo
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$FEDORA_MIRROR/linux/releases/$RELEASE_VERSION/Fedora/$BASE_ARCH/os/ $LOCAL_MIRROR/$FEDORA_IMAGES/
if [ $? -ne 0 ]
then
        echo "Fedora Images FAILED" > $LOG
fi



#Fedora main repo
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$FEDORA_MIRROR/linux/releases/$RELEASE_VERSION/Everything/$BASE_ARCH/os/ $LOCAL_MIRROR/$FEDORA_MAIN/
if [ $? -ne 0 ]
then
	echo "Fedora Main FAILED" > $LOG
fi



#Fedora updates repo
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$FEDORA_MIRROR/linux/updates/$RELEASE_VERSION/$BASE_ARCH/ $LOCAL_MIRROR/$FEDORA_UPDATES/
if [ $? -ne 0 ]
then
	echo "Fedora Updates FAILED" >> $LOG
fi



#RPMFusion free
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$RPMFUSION_MIRROR/$RPMFUSION_FREE/ $LOCAL_MIRROR/$RPMFUSION_FREE/
if [ $? -ne 0 ]
then
	echo "RPMFusion Free FAILED" >> $LOG
fi



#RPMFusion free updates
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$RPMFUSION_MIRROR/$RPMFUSION_FREE_UPDATES/ $LOCAL_MIRROR/$RPMFUSION_FREE_UPDATES/
if [ $? -ne 0 ]
then
	echo "RPMFusion Free Updates FAILED" >> $LOG
fi



#RPMFusion nonfree
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$RPMFUSION_MIRROR/$RPMFUSION_NONFREE/ $LOCAL_MIRROR/$RPMFUSION_NONFREE/
if [ $? -ne 0 ]
then
	echo "RPMFusion NonFree FAILED" >> $LOG
fi



#RPMFusion nonfree updates
rsync -PaH --exclude-from=$EXCLUDES_FILE --numeric-ids --delete --delete-after --delay-updates rsync://$RPMFUSION_MIRROR/$RPMFUSION_NONFREE_UPDATES/ $LOCAL_MIRROR/$RPMFUSION_NONFREE_UPDATES/
if [ $? -ne 0 ]
then
	echo "RPMFusion NonFree Updates FAILED" >> $LOG
fi



#VirtualBox
cd $LOCAL_MIRROR/raw
wget --recursive --timestamping --mirror --level=2 --no-parent http://download.virtualbox.org/virtualbox/rpm/fedora/$RELEASE_VERSION/$BASE_ARCH/
#wget --mirror --level=2 --no-parent http://download.virtualbox.org/virtualbox/rpm/fedora/$RELEASE_VERSION/$BASE_ARCH/
#lftp -c mirror http://download.virtualbox.org/virtualbox/rpm/fedora/$RELEASE_VERSION/$BASE_ARCH/

#rsync -Pa -e "ssh -p 2222" dpadmin@home.christophersmart.com:/data/repos/virtualbox /data/

if [ $? -ne 0 ]
then
	echo "Virtualbox Update FAILED" >> $LOG
fi
cd $OLDPWD	

#Yum rawhide (to enable autoremove)
cd $LOCAL_MIRROR/raw
wget --recursive --timestamping --mirror --level=2 --no-parent http://repos.fedorapeople.org/repos/james/yum-rawhide/fedora-$RELEASE_VERSION/$BASE_ARCH/

if [ $? -ne 0 ]
then
	echo "Yum Rawhide Update FAILED" >> $LOG
fi
cd $OLDPWD	


#Clean up
rm $EXCLUDES_FILE
