#!/bin/bash

#Use ntlm proxy (not needed if using curl)
#export http_proxy="http://localhost:5865"

#Get new definitions
cd /data/updates/clamav/db/
rm *cvd

#Using curl
curl -L --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/cntlm.conf |grep Username |awk {'print $2'}`:`cat /etc/cntlm.conf |grep Password |awk {'print $2'}` http://db.local.clamav.net/main.cvd -o main.cvd
curl -L --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/cntlm.conf |grep Username |awk {'print $2'}`:`cat /etc/cntlm.conf |grep Password |awk {'print $2'}` http://db.local.clamav.net/daily.cvd -o daily.cvd
curl -L --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/cntlm.conf |grep Username |awk {'print $2'}`:`cat /etc/cntlm.conf |grep Password |awk {'print $2'}` http://db.local.clamav.net/bytecode.cvd -o bytecode.cvd

#Using wget (which is unreliable via NTLM)
#wget --no-cache http://db.local.clamav.net/main.cvd
#wget --no-cache http://db.local.clamav.net/daily.cvd

#Copy for local distribution
cp *cvd /var/www/
