#!/bin/bash

export http_proxy="http://localhost:5865"

cd /data/updates/debs

#Ubuntu
debmirror --rsync-options="-aIL --partial --bwlimit=1024 --delete" --ignore-small-errors --nosource --passive --host=mirror.internode.on.net --root=:ubuntu --method=rsync --progress --dist=lucid,lucid-updates,lucid-security,maverick,maverick-updates,maverick-security --section=main,multiverse,restricted,universe --arch=amd64 ubuntu/ --ignore-release-gpg

#Updated Virtualbox
debmirror --rsync-options="-aIL --partial --bwlimit=1024 --delete" --ignore-small-errors --nosource --passive --host=download.virtualbox.org --root=virtualbox/debian --method=http --progress --dist=lucid,maverick --section=non-free --arch=amd64 /data/updates/raw/download.virtualbox.org/virtualbox/deb/ubuntu --ignore-release-gpg

