#!/bin/bash

#Use ntlmaps proxy
#export http_proxy="http://localhost:5865"

#Get new definitions
cd /data/clamav/db/
rm *cvd

#Using curl
curl --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/ntlmaps/server.cfg |grep -i "^USER:" |awk {'print $2'}`:`cat /etc/ntlmaps/server.cfg |grep -i "^PASSWORD:" |awk {'print $2'}` http://db.local.clamav.net/main.cvd -o main.cvd
curl --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/ntlmaps/server.cfg |grep -i "^USER:" |awk {'print $2'}`:`cat /etc/ntlmaps/server.cfg |grep -i "^PASSWORD:" |awk {'print $2'}` http://db.local.clamav.net/daily.cvd -o daily.cvd
curl --proxy 10.0.1.45:80 --proxy-ntlm --proxy-user `cat /etc/ntlmaps/server.cfg |grep -i "^USER:" |awk {'print $2'}`:`cat /etc/ntlmaps/server.cfg |grep -i "^PASSWORD:" |awk {'print $2'}` http://db.local.clamav.net/bytecode.cvd -o bytecode.cvd

#Using wget
#wget --no-cache http://db.local.clamav.net/main.cvd
#wget --no-cache http://db.local.clamav.net/daily.cvd

#Copy for local distribution
cp *cvd /var/www/
